{% set name = "czifile" %}
{% set version = "2026.4.30" %}
{% set python_min = "3.12" %}
{% set sha256 = "83c7022dbef06840b8e306b16769f46ad426b348df61019859ce3a33c0f3aedf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - czifile = czifile.czifile:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - imagecodecs >=2026.3.6
    - tifffile >=2024.8.30
    - xarray >=2024.4.0
    - matplotlib-base >=3.7.0

test:
  imports:
    - czifile
  commands:
    - pip check
    - czifile --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read Carl Zeiss image files (CZI)
  description: |
    Czifile is a Python library for reading image data and metadata from
    Carl Zeiss Image (CZI) files, the native file format of ZEN by
    Carl Zeiss Microscopy GmbH.
  dev_url: https://github.com/cgohlke/czifile/

extra:
  recipe-maintainers:
    - cgohlke
    - csachs
