{% set name = "czifile" %}
{% set version = "2019.7.2.1" %}
{% set sha256 = "6169aa681dd8af0d25e8e731e83393140cb960097d2a641dd145e8349bd2e965" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - czifile = czifile.czifile:main
    - czi2tif = czifile.czi2tif:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.11.3
    - tifffile >=2019.7.2
    - imagecodecs-lite >=2019.12.2

test:
  imports:
    - czifile
  commands:
    - czifile ""
    - czi2tif
  requires:
    - python {{ python_min }}

about:
  home: https://www.lfd.uci.edu/~gohlke/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read Carl Zeiss(r) Image (CZI) files'
  description: |
    Czifile is a Python library to read Carl Zeiss Image (CZI) files,
    the native file format of the ZEN(r) software by Carl Zeiss Microscopy GmbH.
    CZI files contain multidimensional images and metadata from microscopy experiments.
  doc_url: https://www.lfd.uci.edu/~gohlke/
  dev_url: https://github.com/cgohlke/czifile/

extra:
  recipe-maintainers:
    - csachs
